// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as Curry from "../../node_modules/bs-platform/lib/es6/curry.js";
import * as ReactDOMRe from "../../node_modules/reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "../../node_modules/reason-react/src/ReasonReact.js";

function render(domId, comp, _) {
  var eta = Curry._1(comp, /* () */0);
  var e = ReasonReact.element(/* None */0, /* None */0, eta);
  return ReactDOMRe.renderToElementWithId(e, domId);
}

export {
  render ,
  
}
/* ReactDOMRe Not a pure module */
