// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as DOM$Reapp from "./IO/DOM.js";
import * as Playground$Reapp from "./Playground.js";

var id = "root";

console.log("Start...");

DOM$Reapp.render(id, Playground$Reapp.make, /* () */0);

export {
  id ,
  
}
/*  Not a pure module */
