// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "../node_modules/reason-react/src/ReasonReact.js";

var rawComponent = ReasonReact.statelessComponent("Playground");

function make() {
  return /* record */[
          /* debugName */rawComponent[/* debugName */0],
          /* reactClassInternal */rawComponent[/* reactClassInternal */1],
          /* handedOffState */rawComponent[/* handedOffState */2],
          /* willReceiveProps */rawComponent[/* willReceiveProps */3],
          /* didMount */rawComponent[/* didMount */4],
          /* didUpdate */rawComponent[/* didUpdate */5],
          /* willUnmount */rawComponent[/* willUnmount */6],
          /* willUpdate */rawComponent[/* willUpdate */7],
          /* shouldUpdate */rawComponent[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, "hello!");
            }),
          /* initialState */rawComponent[/* initialState */10],
          /* retainedProps */rawComponent[/* retainedProps */11],
          /* reducer */rawComponent[/* reducer */12],
          /* subscriptions */rawComponent[/* subscriptions */13],
          /* jsElementWrapped */rawComponent[/* jsElementWrapped */14]
        ];
}

export {
  rawComponent ,
  make ,
  
}
/* rawComponent Not a pure module */
